
// =============================================================================
// 2. i18n.js
// =============================================================================

/** All UI strings — keys must exist in ar and en */
var TRANSLATIONS = {
    ar: {
        app_name: "AutoConnect",
        nav_home: "الرئيسية",
        nav_services: "خدماتنا",
        nav_emergency: "طوارئ",
        nav_login: "تسجيل الدخول",
        nav_signup: "سجل الآن",
        nav_profile: "الملف الشخصي",
        hero_title_1: "عطلان؟",
        hero_title_2: "متقلقش هنا هتلاقي الي محتاجه",
        hero_sub: "أدخل موقعك واعثر على أقرب ميكانيكي أو قطع غيار أو ونش في دقائق.",
        search_type: "نوع الخدمة",
        search_location: "المنطقة أو المدينة",
        search_btn: "بحث عن خدمة",
        services_title: "خدماتنا",
        services_sub: "اختر نوع الخدمة المناسب لسيارتك أو موتوسيكلك",
        mechanic: "ميكانيكي",
        spare_parts: "قطع غيار",
        towing: "ونش",
        discover_more: "اكتشف المزيد",
        shop_now: "تسوق الآن",
        order_now: "اطلب الآن",
        cta_join_title: "انضم إلى نخبة خبراء السيارات في مصر",
        cta_join_sub: "هل أنت مزود خدمة؟ انضم لشبكتنا واستقبل الطلبات.",
        partner_btn: "انضم إلينا",
        learn_more: "اعرف المزيد",
        login_title: "مرحباً بعودتك",
        login_sub: "قم بتسجيل الدخول للمتابعة في أوتو كونيكت",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        forgot_password: "نسيت كلمة المرور؟",
        login_btn: "تسجيل الدخول",
        or: "أو",
        guest_btn: "المتابعة كضيف",
        no_account: "ليس لديك حساب؟",
        signup_link: "سجل الآن",
        customer: "عميل",
        service_provider: "مزود خدمة",
        register_title: "إنشاء حساب جديد",
        register_sub: "انضم إلى أوتو كونيكت واستفد من خدماتنا المحفوظة",
        register_provider_sub: "سجّل ورشتك وأكمل بيانات محفظة مزود الخدمة",
        full_name: "الاسم الكامل",
        phone: "رقم الهاتف",
        confirm_password: "تأكيد كلمة المرور",
        create_account: "إنشاء حساب",
        have_account: "لديك حساب بالفعل؟",
        continue_guest: "المتابعة كزائر",
        emergency_title: "مساعدة طارئة 🚨",
        emergency_sub: "هل تحتاج إلى مساعدة الآن؟ ابحث عن أقرب ونش واتصل به فوراً.",
        use_location: "استخدام موقعي الحالي",
        or_choose_area: "أو اختر منطقتك يدوياً",
        choose_area: "اختر منطقتك",
        nearest_providers: "أقرب مزودي الخدمة",
        results_by_location: "نتائج بناءً على موقعك",
        open_now: "مفتوح الآن",
        closed: "مغلق",
        call_now: "اتصل الآن",
        view_map: "عرض الموقع",
        emergency_footer: "إذا كنت في خطر وشيك، يرجى الاتصال بخدمات الطوارئ المحلية فوراً (15088). سلامتك هي أولويتنا القصوى.",
        filtered_services: "خدمات مصفاة",
        filtered_sub: "عرض النتائج بناء على اختيارك",
        search_services: "ابحث عن خدمة",
        type: "النوع",
        region: "المنطقة",
        status: "الحالة",
        sort_by: "ترتيب حسب",
        apply_filter: "تطبيق الفلتر",
        showing_results: "عرض",
        results: "نتائج",
        near_you: "بالقرب من موقعك",
        show_map: "عرض الخريطة",
        favorites_title: "المفضلة",
        favorites_sub: "مزودو الخدمة الذين حفظتهم للوصول السريع",
        all_providers: "كل مقدمي الخدمة",
        view_details: "عرض التفاصيل",
        explore_directory: "استكشف الدليل",
        more_services: "هل تبحث عن المزيد من الخدمات؟",
        profile_title: "ملف العميل",
        edit_profile: "تعديل الملف",
        service_summary: "ملخص الخدمة",
        total_visits: "إجمالي الزيارات",
        last_visit: "آخر زيارة",
        next_maintenance: "الصيانة القادمة",
        favorite_providers: "المزودون المفضلون",
        view_all: "عرض الكل",
        add_provider: "إضافة مزود جديد",
        saved_location: "الموقع المحفوظ",
        account_settings: "إعدادات الحساب",
        change_password: "تغيير كلمة المرور",
        notification_prefs: "تفضيلات الإشعارات",
        language_settings: "إعدادات اللغة",
        settings_title: "الإعدادات",
        settings_sub: "قم بتهيئة أمان حسابك وتفضيلاتك",
        account_mgmt: "إدارة الحساب",
        account_mgmt_sub: "إدارة بيانات السيارات الخاصة بك",
        profile_details: "تفاصيل الملف الشخصي",
        security: "الأمان",
        notifications: "الإشعارات",
        upgrade_plan: "ترقية الخطة",
        security_tips: "أفضل ممارسات الأمان",
        tip1: "استخدم 12 حرفاً على الأقل بما في ذلك الرموز.",
        tip2: "قم بتفعيل المصادقة الثنائية (2FA).",
        tip3: "تجنب إعادة استخدام كلمات المرور من منصات أخرى.",
        current_password: "كلمة المرور الحالية",
        new_password: "كلمة المرور الجديدة",
        confirm_new_password: "تأكيد كلمة المرور الجديدة",
        update_password: "تحديث كلمة المرور",
        delete_account: "حذف الحساب",
        delete_account_desc: "حذف الحساب نهائي وسيمحو كل بيانات الأسطول والتشخيص والمخزون من السحابة.",
        delete_my_account: "حذف حسابي",
        provider_reg_title: "انضم لأكبر شبكة خدمات النقل في مصر",
        provider_reg_sub: "سجّل ورشتك وابدأ في استقبال طلبات العملاء القريبين منك.",
        provider_form_title: "بيانات مقدم الخدمة",
        workshop_name: "اسم الورشة / المركز",
        mobile: "رقم الموبايل",
        service_type: "نوع الخدمة",
        availability: "التوفر",
        working_hours: "مواعيد العمل",
        city_area: "المدينة / المنطقة",
        service_desc: "وصف الخدمة (نبذة سريعة)",
        pin_on_map: "حدد مكانك بدقة على الخريطة",
        register_workshop: "سجل ورشتك الآن",
        save_later: "حفظ وإكمال لاحقاً",
        quality_note: "جميع الطلبات يتم مراجعتها لضمان الجودة",
        tech_support: "دعم فني",
        geo_expand: "توسع جغرافي",
        quick_response: "استجابة سريعة",
        live_status: "الحالة المباشرة",
        online_now: "متوفر الآن",
        waiting_time: "وقت الانتظار",
        capacity: "السعة",
        similar_nearby: "خدمات مشابهة قريبة",
        our_location: "موقعنا على الخريطة",
        favorite: "مفضلة",
        privacy: "سياسة الخصوصية",
        terms: "الشروط والأحكام",
        contact: "اتصل بنا",
        copyright: "© 2024 AutoConnect. جميع الحقوق محفوظة.",
        days_ago: "منذ",
        days: "يوم",
        connected: "متصل",
        system_status: "حالة النظام",
        all_types: "الكل",
        status_open: "مفتوح الآن",
        status_closed: "مغلق",
        sort_nearest: "الأقرب",
        sort_rating: "التقييم",
        km_away: "كم",
        loading: "جاري التحميل...",
        no_results: "لا توجد نتائج",
        location_error: "تعذر الحصول على موقعك. اختر المنطقة يدوياً.",
        login_success: "تم تسجيل الدخول (تجريبي)",
        register_success: "تم إنشاء الحساب (تجريبي)",
        password_updated: "تم تحديث كلمة المرور (تجريبي)"
    },
    en: {
        app_name: "AutoConnect",
        nav_home: "Home",
        nav_services: "Our Services",
        nav_emergency: "Emergency",
        nav_login: "Login",
        nav_signup: "Sign Up",
        nav_profile: "Profile",
        hero_title_1: "Broken down?",
        hero_title_2: "Don't worry — find what you need here",
        hero_sub: "Enter your location to find the nearest mechanic, spare parts shop, or tow truck in minutes.",
        search_type: "Service type",
        search_location: "Area or city",
        search_btn: "Search services",
        services_title: "Our Services",
        services_sub: "Choose the right service for your car or motorcycle",
        mechanic: "Mechanic",
        spare_parts: "Spare Parts",
        towing: "Tow Truck",
        discover_more: "Discover more",
        shop_now: "Shop now",
        order_now: "Order now",
        cta_join_title: "Join Egypt's elite automotive experts",
        cta_join_sub: "Are you a service provider? Join our network and receive orders.",
        partner_btn: "Partner with us",
        learn_more: "Learn more",
        login_title: "Welcome back",
        login_sub: "Sign in to continue with AutoConnect",
        email: "Email",
        password: "Password",
        forgot_password: "Forgot password?",
        login_btn: "Sign in",
        or: "or",
        guest_btn: "Continue as guest",
        no_account: "Don't have an account?",
        signup_link: "Sign up now",
        customer: "Customer",
        service_provider: "Service Provider",
        register_title: "Create a new account",
        register_sub: "Join AutoConnect and access our saved services",
        register_provider_sub: "Register your workshop and complete your provider portfolio",
        full_name: "Full name",
        phone: "Phone number",
        confirm_password: "Confirm password",
        create_account: "Create account",
        have_account: "Already have an account?",
        continue_guest: "Continue as guest",
        emergency_title: "Emergency assistance 🚨",
        emergency_sub: "Need help now? Find the nearest tow truck and call immediately.",
        use_location: "Use my current location",
        or_choose_area: "Or choose your area manually",
        choose_area: "Choose your area",
        nearest_providers: "Nearest service providers",
        results_by_location: "Results based on your location",
        open_now: "Open now",
        closed: "Closed",
        call_now: "Call now",
        view_map: "View location",
        emergency_footer: "If you are in immediate danger, call local emergency services (15088). Your safety is our top priority.",
        filtered_services: "Filtered services",
        filtered_sub: "Showing results based on your selection",
        search_services: "Search for services",
        type: "Type",
        region: "Region",
        status: "Status",
        sort_by: "Sort by",
        apply_filter: "Apply filter",
        showing_results: "Showing",
        results: "results",
        near_you: "Near your location",
        show_map: "Show on map",
        favorites_title: "Favorites",
        favorites_sub: "Service providers you saved for quick access",
        all_providers: "All providers",
        view_details: "View details",
        explore_directory: "Explore directory",
        more_services: "Looking for more services?",
        profile_title: "Customer profile",
        edit_profile: "Edit profile",
        service_summary: "Service summary",
        total_visits: "Total visits",
        last_visit: "Last visit",
        next_maintenance: "Next maintenance",
        favorite_providers: "Favorite providers",
        view_all: "View all",
        add_provider: "Add new provider",
        saved_location: "Saved location",
        account_settings: "Account settings",
        change_password: "Change password",
        notification_prefs: "Notification preferences",
        language_settings: "Language settings",
        settings_title: "Settings",
        settings_sub: "Configure your account security and preferences",
        account_mgmt: "Account management",
        account_mgmt_sub: "Manage your vehicle data",
        profile_details: "Profile details",
        security: "Security",
        notifications: "Notifications",
        upgrade_plan: "Upgrade plan",
        security_tips: "Security best practices",
        tip1: "Use at least 12 characters including symbols.",
        tip2: "Enable two-factor authentication (2FA).",
        tip3: "Avoid reusing passwords from other platforms.",
        current_password: "Current password",
        new_password: "New password",
        confirm_new_password: "Confirm new password",
        update_password: "Update password",
        delete_account: "Delete account",
        delete_account_desc: "Deleting your account is permanent and will erase all fleet, diagnostic, and inventory data from the cloud.",
        delete_my_account: "Delete my account",
        provider_reg_title: "Join Egypt's largest transport services network",
        provider_reg_sub: "Register your workshop and start receiving nearby customer requests.",
        provider_form_title: "Service provider information",
        workshop_name: "Workshop / center name",
        mobile: "Mobile number",
        service_type: "Service type",
        availability: "Availability",
        working_hours: "Working hours",
        city_area: "City / area",
        service_desc: "Service description (brief)",
        pin_on_map: "Pin your location on the map",
        register_workshop: "Register your workshop",
        save_later: "Save and complete later",
        quality_note: "All requests are reviewed to ensure quality",
        tech_support: "Technical support",
        geo_expand: "Geographic expansion",
        quick_response: "Quick response",
        live_status: "Live status",
        online_now: "Available now",
        waiting_time: "Waiting time",
        capacity: "Capacity",
        similar_nearby: "Similar services nearby",
        our_location: "Our location on map",
        favorite: "Favorite",
        privacy: "Privacy Policy",
        terms: "Terms & Conditions",
        contact: "Contact us",
        copyright: "© 2024 AutoConnect. All rights reserved.",
        days_ago: "",
        days: "days ago",
        connected: "Connected",
        system_status: "System status",
        all_types: "All",
        status_open: "Open now",
        status_closed: "Closed",
        sort_nearest: "Nearest",
        sort_rating: "Rating",
        km_away: "km away",
        loading: "Loading...",
        no_results: "No results found",
        location_error: "Could not get your location. Please choose your area manually.",
        login_success: "Logged in (demo)",
        register_success: "Account created (demo)",
        password_updated: "Password updated (demo)"
    }
};

/** Active language: "ar" (default) or "en" */
var currentLang = localStorage.getItem("autoconnect_lang") || "ar";

/** Get one translated string by key, e.g. t("login_btn") */
function t(key) {
    var pack = TRANSLATIONS[currentLang];
    return (pack && pack[key]) || TRANSLATIONS.ar[key] || key;
}

/**
 * Switch language: updates body dir (rtl/ltr), all data-i18n elements, and calls
 * onLanguageChange() on the current page if that function exists (e.g. services.js).
 */
function setLanguage(lang) {
    if (!TRANSLATIONS[lang]) return;
    currentLang = lang;
    localStorage.setItem("autoconnect_lang", lang);
    document.body.classList.remove("rtl", "ltr");
    document.body.classList.add(lang === "ar" ? "rtl" : "ltr");
    document.documentElement.lang = lang;

    document.querySelectorAll("[data-i18n]").forEach(function (el) {
        el.textContent = t(el.getAttribute("data-i18n"));
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
        el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
    });

    var toggle = document.getElementById("lang-toggle");
    if (toggle) {
        toggle.textContent = lang === "ar" ? "EN" : "AR";
    }

    if (typeof onLanguageChange === "function") {
        onLanguageChange(lang);
    }
}

/** Flip AR ↔ EN (header button calls this) */
function toggleLanguage() {
    setLanguage(currentLang === "ar" ? "en" : "ar");
}

/**
 * Pick Arabic or English field from API data.
 * Example: getLocalizedField(provider, "name") → name or name_en
 */
function getLocalizedField(obj, field) {
    if (!obj) return "";
    if (currentLang === "en" && obj[field + "_en"]) {
        return obj[field + "_en"];
    }
    return obj[field] || "";
}
